-- HMDM Database Setup Script
-- Run this script as PostgreSQL superuser

DROP DATABASE IF EXISTS hmdm;
DROP USER IF EXISTS hmdm;

CREATE USER hmdm WITH PASSWORD 'CHANGE_THIS_PASSWORD';
CREATE DATABASE hmdm WITH OWNER=hmdm ENCODING='UTF8';
GRANT ALL PRIVILEGES ON DATABASE hmdm TO hmdm;
